### ISSUE TITLE
Docs sidebar download link is broken

### ISSUE THREAD

**Issue by carlosperate** [adafruit/Adafruit_Board_Toolkit#6]
From the Read The Docs documentation https://circuitpython.readthedocs.io/projects/board-toolkit/:
<img width="329" alt="image" src="https://user-images.githubusercontent.com/4189262/119385480-152cd580-bcbe-11eb-978c-26c2af2ebd41.png">

The "Download" link points to https://github.com/adafruit/Adafruit_CircuitPython_Board_Toolkit/releases/latest

Also it'd be nice to have the link to the docs in the README or the GitHub "website" entry next to the description.

**Comment by evaherrada** [comment]
@carlosperate So the README is actually in the **Introduction** section. 

Looks like the name got changed and a few other things didn't

**Comment by evaherrada** [comment]
Assuming I'm write and the name is correct but the links aren't, this should be fixed by #7

**Comment by carlosperate** [comment]
Great, thanks everyone!
